apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: javaapp-network-policy
  namespace: javaapp
spec:
  podSelector:
    matchLabels:
      app: javaapp
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: javaapp
    - podSelector:
        matchLabels:
          app: javaapp
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
